### PR TITLE
Unit and integration tests

### PR DESCRIPTION
**Pull request by tombh**
This implements the boilerplate for both unit-style tests and full end-to-end, cross-browser integration tests.

The unit tests are designed to be lightweight and fast for use in TDD, using React's shallow rendering and no DOM, whether mocked or otherwise. There are only 3 tests at the moment, but test writers will now not be burdened withe overhead of setting up a test environment.

The integration tests will ultimately involve building the entire stack, but this PR uses the default local environment setup of connecting to the catalog's staging API. Again there are only 2 tests but adding more should be trivial no. No excuses!

PS. There's still a failing build for IE. It just looks like the JS is really, really, slow there. Could be a genuine bug we need to look into. I'll keep pushing fixes to this branch.

### CODE REVIEW

**Comment by tombh** [comment]
So everything's green now. I think I might add coverage to this as well and triggered a non-zero exit code if code coverage reduces.

One thing to come from this though is that IE11 is really slow, I had to up the timeout to 5 minutes to get it pass. Whereas Chrome flashes all the tests in about 10 seconds. It may only be a Browserstack thing, but we need to make sure there isn't something badly wrong with the JS in IE...

**Comment by smit1678** [comment]
@tombh 👍 from me. I think this is good to merge if you do. For the CI stuff, do you think it would be worthwhile to just fully switch to Circle to simplify?

**Comment by tombh** [comment]
Ah yes, I forgot to mention that. In my experience integration tests are generally more fragile than unit tests. For instance, tests may fail for seemingly obscure reasons, only to turn green again when rerun with the same code. Also integration tests ultimately should involve the complete setup of an isolated and fully-local instance of the entire stack. So for these reasons I think they deserve to be conceptually distinct from the Travis build.

**Comment by smit1678** [comment]
Makes sense to me. Anything we need to do before we merge this?

**Comment by tombh** [comment]
This is good to go :)

**Pull request merged**
