### PR TITLE
Fix search box CSS for some browsers on some OSs

### PR DESCRIPTION
**Pull request by tombh**
@smit1678 I think this fixes it. Can you try running it locally? Don't wanna have to keep committing to `develop` to see if we've fixed it.

### CODE REVIEW

**Comment by smit1678** [comment]
Seems to be working ok on Firefox (still seeing the square corners though) but still seeing the gap locally on Chrome: 

#### firefox: 
openaerialmap browser 2017-05-25 13-33-00

#### chrome: 
openaerialmap browser 2017-05-25 13-31-16


#### For comparison, current `master` on chrome: 
openaerialmap browser 2017-05-25 13-29-39

**Comment by tombh** [comment]
Well I've had another play with this using the reverse tunnelling thing to view my dev environment on Browserstack and of course I can't reproduce the bug :/ So I wonder if there's wither something to do with the build process, or it's a caching thing with your local browser. The thing to check is, as you said before, the absence of that `display: inline-block` in the wrapping div.

I've pushed a commit with the CSS to round those left hand corners though.

**Comment by smit1678** [comment]
@tombh Nice, this is looking great and it looks like the push you did fixes it. Tested and looks good on Firefox and Chrome locally.

**Comment by tombh** [comment]
Ha great :) At last.

I know that some of the tests are janky here, but would be good to have a general policy of not merging until all tests have passed.

**Comment by smit1678** [comment]
@tombh Agreed on the not merging until tests passing.

**Pull request merged**
