### PR TITLE
Fix #163. Add tms preview when it's available

### LINKED ISSUE #163: Replace thumbnail preview with TMS
Idea: when a TMS for an image is available, load the TMS on the map instead of the thumbnail (currently implemented). If no TMS available yet, just load the thumbnail. 

To consider:

  * If multiple TMS's associated with an image, which TMS is loaded?

My answer to the question would be to default to a TMS that was provided in the metadata when available, otherwise just take the first custom TMS if there are multiple. 

@danielfdsilva Anything else we should consider? Any other interaction or UX considerations here?

### PR DESCRIPTION
**Pull request by danielfdsilva**
This seems to be working as expected but some previews (ex: `http://localhost:3000/#/125.48244953155519,12.04414722606931,14/1323122/55c3b2be2b67227a79b4f4dd`) make the whole world go black. Could we remove those tiles? I think it comes form the tileserver, and not the browser itself.

Ideas?

### CODE REVIEW

**Comment by smit1678** [comment]
@danielfdsilva nice!

> make the whole world go black. Could we remove those tiles?

It looks like it's from those tiles from the OSM France server. I'm not sure how they are rendering those and why they're serving black tiles for areas of no data. No good ideas other than discussing with them about how these tiles were rendered. 

Couple other questions: 

- Are we previewing the custom_tms tiles as well? This looks like it is still the thumbnail preview: 
`http://localhost:3000/#/-80.42221248149872,-0.5977623500267283,17/2100011013203311231/572a320b2b67227a79b4fbea?_k=nyo3m1`

- Have some ideas for how we can handle the green overlay? If you're zoomed, the green overlay is sort of in the way. Is this something we punt on, or something we can address within the UI? 
  - Example: `http://localhost:3000/#/-80.41494369506836,-0.9868324621535585,12/21000110312/571975932b67227a79b4faf5?resolution=high&type=service&_k=cp4mkq`

**Comment by danielfdsilva** [comment]
ok, maybe checking with them is enough.

Right now we're only previewing the thumbnail's tms. Should we preview the custom one as well? How do we pick between the two? How does the user know which one is being previewed? This was is just a reasonable default.

The green overlay indicates the selected cell and I don't think we should remove it / hide it. Moving it to the back would not work either. If the thumbnail/tms is bigger than the cell the the user would loose context of what is selected. Also we should bear in mind that this is only meant to be a preview.

**Comment by smit1678** [comment]
> Should we preview the custom one as well? How do we pick between the two? How does the user know which one is being previewed? This was is just a reasonable default.

Yeah I think it defaults to the main TMS if it has one. If not, then whatever is first in the custom_tms list if it has one. That way, if it has a custom tms, then we at least get a preview of one of them. 

> The green overlay indicates the selected cell and I don't think we should remove it / hide it. Moving it to the back would not work either.

Agreed that we shouldn't get rid of it. What about changing to an outline only with no fill? Also, I think the current implementation puts the thumbnail image on top of the green selection, http://beta.openaerialmap.org/#/125.37483930587767,12.271269155338016,16/132312230032031122/55c3b2be2b67227a79b4f4db?_k=w3vzoj, so I think this is why this has come up and presents a different experience to the user.

**Comment by danielfdsilva** [comment]
Implemented the option discussed in #163.
Waiting a last design input from @ricardomestre

**Comment by danielfdsilva** [comment]
@smit1678 Design review done. Ready for you

**Comment by smit1678** [comment]
@danielfdsilva Thanks. Tested this morning. I'm seeing javascript errors when clicking the custom_tms on this image: http://beta.openaerialmap.org/#/-80.02973556518555,0.10402673728063748,12/03222333222/572b286a2b67227a79b4fbf3?resolution=high&type=service&_k=ronh6l

```
map.js:401 Uncaught TypeError: Cannot read property 'replace' of undefined
```

@ricardomestre Preview buttons look good. Did you have look at the green fill question from earlier as well? Since there is a new experience for a user when using the TMS preview and the green fill is now on top of the TMS, worth discussing more to think through options?

**Comment by smit1678** [comment]
👍  Works well @danielfdsilva. Merging. Let's move the green fill conversation into a ticket.

**Pull request merged**
