### PR TITLE
Add dropdown system

### PR DESCRIPTION
**Pull request by danielfdsilva**
Improve copy to clipboard action

### CODE REVIEW

**Comment by danielfdsilva** [comment]
@smit1678 did you get a chance to have a look at this?

**Comment by smit1678** [comment]
@danielfdsilva No, saw that #53 had unchecked boxes so assumed this wasn't fully finished. Will look at this now.

**Comment by smit1678** [comment]
@danielfdsilva Copy to clipboard looks good. iD and JOSM are next?

**Comment by danielfdsilva** [comment]
I would say we go with this, and then implement those two

**Comment by smit1678** [comment]
:+1:

**Pull request merged**
