### PR TITLE
Feedback modal

### PR DESCRIPTION
**Pull request by danielfdsilva**
- [x] Create feedback for with the appropriate account
- [x] Update field mapping in `feedback_modal.js@103`

### CODE REVIEW

**Comment by DylanMoriarty** [comment]
@danielfdsilva I did a few changes in the above commit.

- The current build of Jeet in the package.json doesn't work. Anchoring it on v6.1.2 works fine. It seems this bug is being worked on by the Jeet folks, so we can keep an eye out and switch back over to the carrot once it's working again.
- The subtext is a bit aggressive when it's in all caps. I gave the copy a softer tone from (WE WANT TO KNOW WHAT YOU THINK to 'YOUR FEEDBACK HELPS US BUILD A BETTER SYSTEM'), but I think we can find a better fit style wise.
- Also grabbed a button class that was missing from the subject question.

**Comment by danielfdsilva** [comment]
@DylanMoriarty nice!
@smit1678 The only thing missing here is creating the feedback form the appropriate account and update the field mapping.

**Comment by smit1678** [comment]
👍  Working on the right account for the form now. 

@DylanMoriarty @danielfdsilva Should we also add in the pre-filled report link in the map area: https://github.com/hotosm/oam-browser/issues/140#issuecomment-225962710?

**Comment by danielfdsilva** [comment]
All done. I'd say :shipit:

**Pull request merged**
